// TODO: alias plugins for common use cases, e.g. fiona.surname vs fiona.lastname
// TODO: configuration plugins for common use case, e.g. fiona.float() vs fiona.number({ precision: 2 })
require('./array/fiona.array')
require('./number/fiona.number')
require('./choose/fiona.choose')
require('./choose/fiona.choose-oneof')
require('./regex/fiona.regex')
require('./name/fiona.name')
require('./duplicable/fiona.duplicable')
require('./bool/fiona.bool')
require('./json/fiona.json')
require('./lorem/fiona.lorem')
require('./string/fiona.string')
require('./date/fiona.date')
require('./weighted/fiona.weighted')
require('./find/fiona.find')
require('./shuffle/fiona.shuffle')
